# Generated by Django 4.1.7 on 2023-03-31 06:40

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Школа')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[main.utils.validate_phone_number], verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Предмет')),
            ],
        ),
    ]
